### ISSUE TITLE
docs: Kubernetes v1.11: need to update the method to figure out MountPropagation setting

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn#216]
`MountPropagation` no longer exists in the `ps aux|grep kube` for v1.11, but the feature seems enabled by detecting it directly through a testing pod with `MountPropagation: Bidirectional`.

e.g.
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-mount-test
spec:
  containers:
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: test
    args: ["/bin/sh", "-c", "sleep 1000000000"]
    volumeMounts:
    - name: mountpoint
      mountPath: /mnt/tmp
      mountPropagation: Bidirectional
    securityContext:
      privileged: true
  volumes:
  - name: mountpoint
    hostPath:
        path: /mnt/tmp
```

So this no longer applied: https://github.com/rancher/longhorn/tree/v0.3-rc#check-if-your-setup-satisfied-csi-requirement

We need to figure out another way to let the user know if mount propagation is enabled.

At least we can run a test daemonset based on above the yaml. It's better to be a simple script that user can run and validate. And better to be done outside of Longhorn.
