### ISSUE TITLE
volumeattachments - csi not found after redeploying a workload

### ISSUE THREAD

**Issue by PhilippHeuer** [rancher/longhorn#267]
## Description

To be honest im not exactly sure what the error is, i noticed this when i redeployed a workload that was fixed on a specific node (required affinity on the hostname) that the longhorn volume mount stops working with this error message:
```
MountVolume.WaitForAttach failed for volume "pvc-652a7f2a-aa56-11e8-ad33-001c42c2325f" : volumeattachments.storage.k8s.io "csi-ac63c8ac5d85e1e3347a4de29f9494490e5729518a7a83d55a48307c71acf7f7" not found
```

## Reproduce

- Modify the hostname in the provided deployment example to to a existing one in your cluster for the tests, it's required that the pod gets scheduled on the same node again
- Deploy the deployment/pvc
- Modify the example environment variable in the deployment to trigger an update
- (if still working: remove the running pod so it's recreated)
- New pod won't be able to start and throws this error message:
```
MountVolume.WaitForAttach failed for volume "pvc-652a7f2a-aa56-11e8-ad33-001c42c2325f" : volumeattachments.storage.k8s.io "csi-ac63c8ac5d85e1e3347a4de29f9494490e5729518a7a83d55a48307c71acf7f7" not found
```

## Environment

Rancher: v2.0.8
Kubernetes: RKE - v1.11.1-rancher1-1 (on CentOS 7.4 / Cancal)
Docker: 18.06.1-ce

## Deployment

```
---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # affinity
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node-73505
      # container
      containers:
      - name: nginx
        image: nginx:1.15-alpine
        # published ports
        ports:
        - containerPort: 80
        # environement
        env:
        - name: EXAMPLE
          value: "example"
        # data mounts
        volumeMounts:
        - name: data
          mountPath: /var/www/html
      # Volumes
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nginx-pvc
---
# Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
```
