### ISSUE TITLE
Is there any way to set a proper name of volume during Persistent Volume creation?

### ISSUE THREAD

**Issue by lnikell** [rancher/longhorn#270]
I'm using Rancher 2.0.6 and installed longhorn. I have longhorn as a default class and I see it in rancher. When I'm trying to create a new Persistent Volume through the rancher UI, I see the volume in the rancher UI but nothing was created in Longhorn. If I do the same through the command line with the command like this: 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
```

It creates volume in longhorn + I see it in Rancher, but the name of the volume is not something human readable, also after that, I can't edit description field through the UI of Rancher and getting error if I try.

So what should be the right approach to actually get a human-readable volume name which I would be able to see in longhorn?
