### ISSUE TITLE
Update documentation of backup to S3 and minio yaml

### ISSUE THREAD

**Issue by lnikell** [rancher/longhorn#279]
We should have more information about backup to S3 option, because existing docs are not enough to get it up and running. 

`kubectl create -f https://raw.githubusercontent.com/rancher/longhorn/master/deploy/backupstores/minio-backupstore.yaml`

- If you run the script above configuration will cause crashing of rancher UI. It should be I guess creation of Deployment rather than a single pod.
- No namespace for service
- I think there is no need of creating two secrets, just one in the namespace the same as longhorn placed 
```
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bG9uZ2hvcm4tdGVzdC1hY2Nlc3Mta2V5 # longhorn-test-access-key
  AWS_SECRET_ACCESS_KEY: bG9uZ2hvcm4tdGVzdC1zZWNyZXQta2V5 # longhorn-test-secret-key
  AWS_ENDPOINTS: aHR0cDovL21pbmlvLXNlcnZpY2UuZGVmYXVsdDo5MDAw # http://minio-service.default:9000
---
# same secret for longhorn-system namespace
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bG9uZ2hvcm4tdGVzdC1hY2Nlc3Mta2V5 # longhorn-test-access-key
  AWS_SECRET_ACCESS_KEY: bG9uZ2hvcm4tdGVzdC1zZWNyZXQta2V5 # longhorn-test-secret-key
  AWS_ENDPOINTS: aHR0cDovL21pbmlvLXNlcnZpY2UuZGVmYXVsdDo5MDAw # http://minio-service.default:9000
```
- Add to the documentation what to do if the bucket name is not `backupbucket`, because container with minio have cmd which also depends on the bucketname
```
mkdir -p /storage/{{your bucket name}} && exec /usr/bin/minio server /storage
```
- Ideally add example of required permission policies for AWS IAM User

After debuging and fixes I was able to set up minio and connect it to longhorn without getting errors in UI, but backups still does not work for me and I see the following error in minio logs when I try to create a backup:

```
API: SYSTEM()
Time: 21:00:12 UTC 09/05/2018
Error: file not found
```
