### ISSUE TITLE
[Question] Resizing a volume

### ISSUE THREAD

**Issue by Angelinsky7** [rancher/longhorn#317]
Hi, i would like to resize a volume created with longhorn.
Is longhorn compatible with resiszing a volume ?
What is the correct procedure ?
I tried to change the pvc and restart the pod, but the pvc stays in resizing state...

From : 
```
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
to : 
```
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```
and the state is now : 
```
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-10-29T11:20:33Z
    status: "True"
    type: Resizing
  phase: Bound
```

Could someone guide me thought this ?
Thanks you very much !!!
