### ISSUE TITLE
MountVolume failed rpc error

### ISSUE THREAD

**Issue by lucevers** [rancher/longhorn#336]

**Comment by lucevers** [comment]
**Version Information**
   Server Ubuntu version 18.04.1 LTS
   Kernal: 4.15.0-38
   Docker version: 18.6.1
   Rancher/kubernetes V1.11.3
   Kubectl version: V 1.10.1
   Longhorn CSI
   Longhorn-engine: V0.3.0
   Longhorn-manager: V0.3.2

  3 jobs are started, they are using the same PVC.
  

In attach info and logging.
[error.txt](https://github.com/rancher/longhorn/files/2612050/error.txt)

**Comment by yasker** [comment]
@lucevers The configuration of access mode is wrong. Can you correct it and try again? I think it confused the Kubernetes.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sshpollerpvc
  namespace: eor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
```

Longhorn is `ReadWriteOnce`, not `ReadWriteMany`. It's similar to EBS, rather than NFS/EFS.

See the example at https://github.com/rancher/longhorn#use-longhorn-with-kubernetes
