### ISSUE TITLE
longhorn-driver-deployer hangs with 'PodInitializing'

### ISSUE THREAD

**Issue by Angelinsky7** [rancher/longhorn#352]
Hi,
i'm trying to install on a new node longhorn 0.3.2 and the longhorn-driver-deployer hangs in the state 'PodInitializing' without doing nothing...
sadly i don't know where i could find a log message to guide me solve this.
my installation pass the requirements with the Environment check script...
i tried with csi and flexvolume

this is the pod events : 

```
Normal | Scheduled | Successfully assigned longhorn-system/longhorn-driver-deployer-6d9765fd59-vhp2b to node01 | 26 minutes ago
-- | -- | -- | --
Normal | Pulled | Container image "rancher/longhorn-manager:v0.3.2" already present on machine | 26 minutes ago
Normal | Created | Created container | 26 minutes ago
Normal | Started | Started container | 26 minutes ago
```

the node info : 
```
Rancher | v2.1.4
User Interface | v2.1.18
Helm | v2.10.0-rancher5
Machine | v0.15.0-rancher1-1
kubernetes_version: "v1.11.5-rancher1-1"
```

thanks for you help, i would happily give you more info

**Comment by Angelinsky7** [comment]
If i deactivate 'Project Network Isolation' in Rancher everything is working fine...
So it's clearly not an issue with longhorn... sorry
If someone knows how to configure a namspace/project to override the setting it would be greate

**Comment by yasker** [comment]
@Angelinsky7 It's due to `longhorn-driver-deployer` cannot talk to the Longhorn manager API. So it makes sense that it's a network related issue.

Though to my understanding (https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/), `Project Network Isolation` only applies to the network between projects. Can you check what's the log in the Longhorn manager? Is it complaining about cannot access certain resources?

**Comment by Angelinsky7** [comment]
yeah exactly, the issue is that the driver cannot talk to the manager thought the service discovery name... if i try with the ip of the manager with a curl command everything is fine, but if i try with the dns name, no response. If i deactivate Project Network Isolation it's working again...
It clearly seems that is a docker configuration issue.

**Comment by Xe** [comment]
I just ran into this while trying to deploy Longhorn on my Talos Linux homelab. How should I diagnose this? There's no useful logs other than the Longhorn pod is initializing.

**Comment by Xe** [comment]
Turns out I needed to annotate the namespace with the following labels:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
```
