### ISSUE TITLE
Backup configuration - default setting or label-based?

### ISSUE THREAD

**Issue by sebastiansirch** [rancher/longhorn#362]
Currently, backups can only be configured by manually approaching the UI.

Two ideas for improvement:
* Provide a default configuration applied to all volumes (e.g. to have a weekly backup by default)
* Or even provide a configuration based on labels, i.e. the PVC could have multiple labels about backup intervals etc. and longhorn could use them to configure its internal backup mechanism.

**Comment by yasker** [comment]
Hi @sebastiansirch 

Those ideas sound nice.

1. This one can definitely be done.
2. Currently, Longhorn doesn't have the permission to look into PVC object directly. Though we should able to provide a way to set a backup policy in the storage class. And in the future, we may able to look into PVCs in order to provide more visibility to the workload.

**Comment by sebastiansirch** [comment]
Yep, I like the idea with the storage class even more than attaching those labels to the PVC 👍

**Comment by sebastiansirch** [comment]
Hi @yasker, 
in the meanwhile, is there a way to configure the backup settings of a volume via the REST API (i.e. create a new backup schedule for a specific volume)? Then it would be easy to write a small script to apply default backup settings via a cronjob.

**Comment by yasker** [comment]
@sebastiansirch We do have API to config backup settings of a volume. An example can be found at https://github.com/rancher/longhorn-tests/blob/master/manager/integration/tests/test_recurring_job.py#L10 .

**Comment by yasker** [comment]
For now, we're going to deal with the second point first.

We will add the ability to set up recurring backup/snapshot using the storage class or volume directly.

**Comment by meldafrawi** [comment]
- [ ]  Create StorageClass with default snapshot and Backup configurations, Using
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: rancher.io/longhorn
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  recurringJobs:  '[{"name":"snap", "task":"snapshot", "cron":"*/1 * * * *", "retain":1},
                   {"name":"backup", "task":"backup", "cron":"*/2 * * * *", "retain":1}]'

```
