### ISSUE TITLE
Change default replica count configuration does not take effect

### ISSUE THREAD

**Issue by vincent927** [rancher/longhorn#440]
I have modified the number of default replica count to 1, but it does not take effect. Whether it is an old volume or a newly created volume。

v 0.4.0

**Comment by yasker** [comment]
@vincent927 In case of using Kubernetes driver, you need to update the storageclass configuration:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: rancher.io/longhorn
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
```

Change the `numberOfReplicas` above to `1` in your case.
