### ISSUE TITLE
claim.Spec.Selector is not supported

### ISSUE THREAD

**Issue by lucevers** [rancher/longhorn#72]
**Problem with StatefulSets**

  Example:  An RKE cluster with 3 servers.
                   To start a StatefulSet you need more than one PVC for the same SatefulSet object.

  In the StatefulSet you cannot use the 'claimedname' because there are more than one PVC's.
```
volumes:
      - name: data
        persistentVolumeClaim:
          **claimName: longhorn-pvc-deploy**
```
  Only possible by selecting via labels 

  Example PVC's: As an example, I changed the statefulset kubia example from the book:  "Kubernetes in Action"
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      **app: kubia**
      podindex: "0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      **app: kubia**
      podindex: "1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: kubia
      podindex: "2"
```
 I'm using the storageclass described by the Longhorn Github site.
```
**Error**:
 Warning  ProvisioningFailed    1m (x11 over 13m)   rancher.io/longhorn longhorn-manager-bbxr7 684e4862-61a4-11e8-b0ca-0a580a2a0204  Failed to provision volume with StorageClass "longhorn": claim.Spec.Selector is not supported
```
Without a Selector you cannot use a StatefulSet with Longhorn.
Or are there other possibilities which I don't know?
