### ISSUE TITLE
Deploy not use the volumes

### ISSUE THREAD

**Issue by CrisMon-01** [rancher/longhorn#74]
I have create this storage class:
```
kubectl describe storageclass longhorn 
Name:                  longhorn
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           rancher.io/longhorn
Parameters:            fromBackup=,numberOfReplicas=3,staleReplicaTimeout=30
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

this pvc:
 ```
kubectl describe persistentvolumeclaim longhorn-volv-pvc 
Name:          longhorn-volv-pvc
Namespace:     default
StorageClass:  longhorn
Status:        Bound
Volume:        pvc-120b8156-6345-11e8-8a4d-080027ed4615
Labels:        <none>
Annotations:   control-plane.alpha.kubernetes.io/leader={"holderIdentity":"c8a222fe-6342-11e8-bd58-5a7b9f6a035e","leaseDurationSeconds":15,"acquireTime":"2018-05-29T13:34:54Z","renewTime":"2018-05-29T13:34:56Z","lea...
               pv.kubernetes.io/bind-completed=yes
               pv.kubernetes.io/bound-by-controller=yes
               volume.beta.kubernetes.io/storage-provisioner=rancher.io/longhorn
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      97660Ki
Access Modes:  RWO
Events:        <none>
```

and i have this deployment, with that i want to use the storage class to have a dinamic provisioning:
 ```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbloginnfs
  labels:
    db: dbnfs
spec:
  replicas: 1
  selector:
    matchLabels:
      db: dbnfs
  template:
    metadata:
      labels:
        db: dbnfs
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "dbutenti"
        volumeMounts:
        - mountPath: "var/lib/mysql"
          name: longhorn
      volumes:
      - name: longhorn
        persistentVolumeClaim:
          claimName: longhorn-volv-pvc
```

but the deployment not work because it return this:
 ```
kubectl describe pod dbloginnfs-764d6864d9-rc8x9 
Name:           dbloginnfs-764d6864d9-rc8x9
Namespace:      default
Node:           vmhost2-virtualbox/192.168.99.102
Start Time:     Tue, 29 May 2018 16:03:41 +0200
Labels:         db=dbnfs
                pod-template-hash=3208242085
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  ReplicaSet/dbloginnfs-764d6864d9
Containers:
  mysql:
    Container ID:   
    Image:          mysql:5.7
    Image ID:       
    Port:           3306/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      MYSQL_ROOT_PASSWORD:  root
      MYSQL_DATABASE:       dbutenti
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-zwqh5 (ro)
      var/lib/mysql from longhorn (rw)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  longhorn:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  longhorn-volv-pvc
    ReadOnly:   false
  default-token-zwqh5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-zwqh5
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age               From                         Message
  ----     ------                 ----              ----                         -------
  Normal   Scheduled              4m                default-scheduler            Successfully assigned dbloginnfs-764d6864d9-rc8x9 to vmhost2-virtualbox
  Normal   SuccessfulMountVolume  4m                kubelet, vmhost2-virtualbox  MountVolume.SetUp succeeded for volume "default-token-zwqh5"
  Warning  FailedMount            18s (x2 over 2m)  kubelet, vmhost2-virtualbox  Unable to mount volumes for pod "dbloginnfs-764d6864d9-rc8x9_default(17e44dcb-6349-11e8-8a4d-080027ed4615)": timeout expired waiting for volumes to attach or mount for pod "default"/"dbloginnfs-764d6864d9-rc8x9". list of unmounted volumes=[longhorn]. list of unattached volumes=[longhorn default-token-zwqh5]
```

how can i solve it?
@yasker
