### ISSUE TITLE
Replicas on same host

### ISSUE THREAD

**Issue by saschaarthur** [rancher/longhorn#77]
Hello,

Today i figured out that longhorn schedules replicas on the same host.

![grafik](https://user-images.githubusercontent.com/4057921/40846044-b98f1e2c-65b8-11e8-8d89-655a7bd2d722.png)

Should be fixed asap ~

**Comment by yasker** [comment]
hi @saschaarthur 

We cannot look into this if there is no log or reproduce steps.

We're using the Kubernetes scheduler to do soft anti-affinity scheduling. If it's impossible to schedule on the other hosts, the scheduler will schedule both replicas in one host.

You can check the replica pods (`<volume_name>-r-xxxx`) and they should have the following in the spec for soft anti-affinity rules:

```
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              longhorn-volume-replica: <volume_name>
          topologyKey: kubernetes.io/hostname
        weight: 100
```
