### ISSUE TITLE
Can't mount longhorn to pod

### ISSUE THREAD

**Issue by andymelichar** [rancher/longhorn#92]
Rancher 2.0
Ubuntu 16.04
Docker 17.03.2-ce
Longhorn UI installed
RKE v0.1.8-rc5

Trying to spin up a mysql pod with longhorn share using a statefulset. In the Longhorn UI I can see the mount and can attach it manually, doesn't affect the pod initializing though, still sits in init and the data share fails to mount.

StorageClass:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
provisioner: rancher.io/longhorn
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""

```

StatefulSet volume settings:
```
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: mysql
      - name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 5Gi
```

When spun up, it just sits in pending and eventually errors out with
```
Warning  FailedMount            1m (x6 over 12m)     kubelet, 159.89.155.122  Unable to mount volumes for pod "mysql-0_default(ff629083-77fb-11e8-8592-dea6a6e8a9dd)": timeout expired waiting for volumes to attach or mount for pod "default"/"mysql-0". list of unmounted volumes=[data]. list of unattached volumes=[data conf config-map default-token-5tg42]
```

**Comment by andymelichar** [comment]
Further info. Trashed my entire cluster and started over, using the example statefulset.yaml doesn't work either. Steps to reproduce:
```
root@jumpserver-nyc3:~# ./rke up --config rancher-cluster.yml
```
rancher-cluster.yml
```
nodes:
  - address: <node_ip>
    user: root
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa
  - address: <node_ip>
    user: root
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa
  - address: <node_ip>
    user: root
    role: [controlplane,etcd,worker]
    ssh_key_path: ~/.ssh/id_rsa

addons: |-
  ---
  kind: Namespace
  apiVersion: v1
  metadata:
    name: cattle-system
  ---
  kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: cattle-admin
    namespace: cattle-system
  ---
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: cattle-crb
    namespace: cattle-system
  subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-ingress
    namespace: cattle-system
  type: Opaque
  data:
    tls.crt: <tlscert>
    tls.key: <tlskey>
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: cattle-keys-server
    namespace: cattle-system
  type: Opaque
  data:
    cacerts.pem: <cacert>
  ---
  apiVersion: v1
  kind: Service
  metadata:
    namespace: cattle-system
    name: cattle-service
    labels:
      app: cattle
  spec:
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    selector:
      app: cattle
  ---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    namespace: cattle-system
    name: cattle-ingress-http
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"   # Max time in seconds for ws to remain shell window open
      nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"   # Max time in seconds for ws to remain shell window open
  spec:
    rules:
    - host: <FQDN>
      http:
        paths:
        - backend:
            serviceName: cattle-service
            servicePort: 80
    tls:
    - secretName: cattle-keys-ingress
      hosts:
      - <FQDN>
  ---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:latest
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/rancher/ssl
            name: cattle-keys-volume
            readOnly: true
        volumes:
        - name: cattle-keys-volume
          secret:
            defaultMode: 420
            secretName: cattle-keys-server
services:
  kubelet:
    extra_args:
      volume-plugin-dir: /var/lib/kubelet/volumeplugins
```

Install Longhorn:
```
kubectl create -f https://raw.githubusercontent.com/rancher/longhorn/master/deploy/longhorn.yaml
```

Add "longhorn" storageclass in cluster UI.

Attempt to set up statefulset example:
```
kubectl create -f https://raw.githubusercontent.com/rancher/longhorn/master/examples/statefulset.yaml
```

Still fails to mount:
```
root@jumpserver-nyc3:~# kubectl describe pod web
Name:           web-0
Namespace:      default
Node:           <nodeip>/<nodeip>
Start Time:     Mon, 25 Jun 2018 14:53:35 +0000
Labels:         app=nginx
                controller-revision-hash=web-6596ffb49b
                statefulset.kubernetes.io/pod-name=web-0
Annotations:    field.cattle.io/publicEndpoints=[{"addresses":["<nodeip>"],"port":32141,"protocol":"TCP","serviceName":"default:nginx","allNodes":true}]
Status:         Pending
IP:
Controlled By:  StatefulSet/web
Containers:
  nginx:
    Container ID:
    Image:          k8s.gcr.io/nginx-slim:0.8
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /usr/share/nginx/html from www (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-dsnb4 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  www:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  www-web-0
    ReadOnly:   false
  default-token-dsnb4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-dsnb4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age               From                     Message
  ----     ------                 ----              ----                     -------
  Normal   Scheduled              18m               default-scheduler        Successfully assigned web-0 to 159.89.155.122
  Normal   SuccessfulMountVolume  18m               kubelet, <nodeip>  MountVolume.SetUp succeeded for volume "default-token-dsnb4"
  Warning  FailedMount            2m (x8 over 16m)  kubelet, <nodeip>  Unable to mount volumes for pod "web-0_default(8916e4fc-7887-11e8-a9d4-926a14ffab5e)": timeout expired waiting for volumes to attach or mount for pod "default"/"web-0". list of unmounted volumes=[www]. list of unattached volumes=[www default-token-dsnb4]
```
